## LOADING LIBRARIES

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

import sklearn
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

## LOAD DATASET

In [2]:
file = "dataset/student_module_pass_chance_regression.csv"
df = pd.read_csv(file)
df.head()

,Student_ID,Gender,Attendance_Percentage,Assignment_Average,Quiz_Average,Midterm_Marks,Study_Hours_Per_Week,Previous_Module_Marks,Class_Participation_Score,Missed_Assignments,LMS_Activity_Hours_Per_Week,Pass_Chance_Percentage
0,ST0001,Female,91.8,79.0,77.5,75.1,7.2,69.8,10.0,2,8.8,76.82
1,ST0002,Male,64.7,44.9,81.3,54.1,7.1,58.8,1.8,5,9.3,35.13
2,ST0003,Female,34.9,37.4,61.0,31.0,13.0,51.8,1.4,6,10.2,25.48
3,ST0004,Female,49.5,44.6,33.6,44.1,1.0,78.1,4.8,4,4.1,32.98
4,ST0005,Male,97.3,92.5,100.0,100.0,4.2,100.0,10.0,1,7.2,91.71

In [3]:
encode = LabelEncoder()
df['Gender'] = encode.fit_transform(df['Gender'])

In [4]:
df.head()

,Student_ID,Gender,Attendance_Percentage,Assignment_Average,Quiz_Average,Midterm_Marks,Study_Hours_Per_Week,Previous_Module_Marks,Class_Participation_Score,Missed_Assignments,LMS_Activity_Hours_Per_Week,Pass_Chance_Percentage
0,ST0001,0,91.8,79.0,77.5,75.1,7.2,69.8,10.0,2,8.8,76.82
1,ST0002,1,64.7,44.9,81.3,54.1,7.1,58.8,1.8,5,9.3,35.13
2,ST0003,0,34.9,37.4,61.0,31.0,13.0,51.8,1.4,6,10.2,25.48
3,ST0004,0,49.5,44.6,33.6,44.1,1.0,78.1,4.8,4,4.1,32.98
4,ST0005,1,97.3,92.5,100.0,100.0,4.2,100.0,10.0,1,7.2,91.71

In [5]:
df = df.drop(['Student_ID'], axis=1)

In [6]:
df.isna().sum()

Gender                          0
Attendance_Percentage          45
Assignment_Average             45
Quiz_Average                   45
Midterm_Marks                   0
Study_Hours_Per_Week           45
Previous_Module_Marks          45
Class_Participation_Score       0
Missed_Assignments              0
LMS_Activity_Hours_Per_Week    45
Pass_Chance_Percentage          0
dtype: int64

## DETECT OUTLIERS USING IQR

In [7]:
# Select numerical columns
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

# Detect outliers using IQR
for column in numerical_columns:
    
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    ]
    
    print(f"{column}: {len(outliers)} outliers")

Gender: 0 outliers
Attendance_Percentage: 15 outliers
Assignment_Average: 16 outliers
Quiz_Average: 14 outliers
Midterm_Marks: 8 outliers
Study_Hours_Per_Week: 76 outliers
Previous_Module_Marks: 11 outliers
Class_Participation_Score: 0 outliers
Missed_Assignments: 24 outliers
LMS_Activity_Hours_Per_Week: 39 outliers
Pass_Chance_Percentage: 21 outliers

## HANDLE MISSING VALUES USING MEDIAN BCZ ALL FEATURES CONTAIN OUTLIERS

In [8]:
df[numerical_columns] = df[numerical_columns].fillna(
    df[numerical_columns].median()
)

In [9]:
df.isna().sum()

Gender                         0
Attendance_Percentage          0
Assignment_Average             0
Quiz_Average                   0
Midterm_Marks                  0
Study_Hours_Per_Week           0
Previous_Module_Marks          0
Class_Participation_Score      0
Missed_Assignments             0
LMS_Activity_Hours_Per_Week    0
Pass_Chance_Percentage         0
dtype: int64

## REMOVE ALL DETECTED OUTLIERS

In [10]:

print("Dataset before removing outliers:", df.shape)

# Remove outliers using IQR
for column in numerical_columns:
    
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    df = df[
        (df[column] >= lower_bound) &
        (df[column] <= upper_bound)
    ]

print("Dataset after removing outliers:", df.shape)
df.reset_index(drop=True, inplace=True)

df.head()

Dataset before removing outliers: (3000, 11)
Dataset after removing outliers: (2791, 11)

,Gender,Attendance_Percentage,Assignment_Average,Quiz_Average,Midterm_Marks,Study_Hours_Per_Week,Previous_Module_Marks,Class_Participation_Score,Missed_Assignments,LMS_Activity_Hours_Per_Week,Pass_Chance_Percentage
0,0,91.8,79.0,77.5,75.1,7.2,69.8,10.0,2,8.8,76.82
1,1,64.7,44.9,81.3,54.1,7.1,58.8,1.8,5,9.3,35.13
2,1,97.3,92.5,100.0,100.0,4.2,100.0,10.0,1,7.2,91.71
3,0,70.0,72.9,89.6,78.9,8.8,60.8,8.2,5,6.1,57.93
4,0,64.7,75.7,55.9,85.0,3.7,44.4,6.8,2,7.7,63.29

## Feature splitting

In [11]:
X = df.drop(['Pass_Chance_Percentage'], axis=1)
y = df['Pass_Chance_Percentage']
print(X)
print(y)

      Gender  Attendance_Percentage  Assignment_Average  Quiz_Average  \
0          0                   91.8                79.0          77.5
1          1                   64.7                44.9          81.3
2          1                   97.3                92.5         100.0
3          0                   70.0                72.9          89.6
4          0                   64.7                75.7          55.9
...      ...                    ...                 ...           ...
2786       1                   84.9                72.1          71.4
2787       0                   78.6                63.7          59.2
2788       1                   83.9                88.2          91.2
2789       0                   65.6                47.7          52.7
2790       1                   72.3                56.6          59.8

      Midterm_Marks  Study_Hours_Per_Week  Previous_Module_Marks  \
0              75.1                   7.2                   69.8
1              54.1                   7.1                   58.8
2             100.0                   4.2                  100.0
3              78.9                   8.8                   60.8
4              85.0                   3.7                   44.4
...             ...                   ...                    ...
2786           81.2                   2.3                   58.2
2787           63.1                   2.4                   51.4
2788          100.0                   4.0                   43.9
2789           76.8                   7.7                   65.9
2790           56.0                   2.2                   77.0

      Class_Participation_Score  Missed_Assignments  \
0                          10.0                   2
1                           1.8                   5
2                          10.0                   1
3                           8.2                   5
4                           6.8                   2
...                         ...                 ...
2786                       10.0                   2
2787                        6.2                   1
2788                        8.8                   1
2789                        7.0                   4
2790                        6.3                   0

      LMS_Activity_Hours_Per_Week
0                             8.8
1                             9.3
2                             7.2
3                             6.1
4                             7.7
...                           ...
2786                          6.0
2787                          0.7
2788                          5.6
2789                         10.6
2790                          8.2

[2791 rows x 10 columns]
0       76.82
1       35.13
2       91.71
3       57.93
4       63.29
        ...
2786    67.01
2787    52.48
2788    71.61
2789    60.40
2790    65.28
Name: Pass_Chance_Percentage, Length: 2791, dtype: float64

## SPLIT DATASET

In [12]:
X_train, X_test, y_train,y_test=train_test_split(X, y, test_size=.2, random_state=42)
X_train.shape

(2232, 10)

In [13]:
X_test.shape

(559, 10)

## Scale our data to prevent data leakage during model testing

In [14]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train

,Gender,Attendance_Percentage,Assignment_Average,Quiz_Average,Midterm_Marks,Study_Hours_Per_Week,Previous_Module_Marks,Class_Participation_Score,Missed_Assignments,LMS_Activity_Hours_Per_Week
1644,1,92.2,72.6,89.4,85.3,13.0,87.4,4.6,2,10.9
2389,1,68.6,69.4,71.3,60.6,8.4,80.2,4.9,4,9.9
1807,1,69.3,79.2,69.3,66.6,14.8,47.0,5.4,2,13.6
100,0,62.7,47.4,45.5,59.7,8.6,69.7,7.1,1,13.0
315,0,92.2,84.7,83.0,81.7,5.2,79.9,7.9,2,7.1
...,...,...,...,...,...,...,...,...,...,...
1638,0,80.0,58.1,79.6,53.8,6.7,72.4,3.5,0,5.7
1095,0,78.6,54.7,55.3,41.4,9.7,62.1,8.4,2,11.5
1130,1,60.9,100.0,79.9,81.6,12.2,69.7,4.8,2,10.8
1294,0,85.2,59.3,88.9,78.2,12.8,78.6,9.4,1,11.1
860,1,84.9,93.4,88.9,83.2,7.8,67.7,10.0,2,9.6

In [15]:
X_test

,Gender,Attendance_Percentage,Assignment_Average,Quiz_Average,Midterm_Marks,Study_Hours_Per_Week,Previous_Module_Marks,Class_Participation_Score,Missed_Assignments,LMS_Activity_Hours_Per_Week
2764,1,72.4,73.2,80.4,70.0,7.7,72.1,5.5,0,5.8
2270,0,75.8,47.0,56.9,69.1,11.7,67.8,4.9,0,14.2
1993,0,100.0,63.7,75.2,71.5,3.8,64.4,8.9,2,11.1
2462,0,74.8,77.5,77.9,96.0,9.5,55.8,8.1,2,15.1
2130,0,89.9,60.9,70.6,55.8,5.0,86.4,8.4,1,7.1
...,...,...,...,...,...,...,...,...,...,...
2518,0,93.3,89.2,61.9,89.6,8.4,76.4,9.4,0,9.3
157,0,60.8,60.8,83.5,69.1,7.9,52.3,2.1,6,9.8
2566,0,96.6,73.6,85.3,80.3,14.8,65.1,9.2,1,14.0
2003,0,72.7,54.0,50.3,72.5,7.2,73.6,5.8,3,8.5
238,0,55.6,59.8,73.8,51.2,7.7,60.6,7.2,3,6.7

## Model selection

## LINEAR REGRESSION

In [16]:
model_lr = LinearRegression()
model_lr.fit(X_train_scaled, y_train)

LinearRegression()

In [17]:
y_lr_pred = model_lr.predict(X_test_scaled)
# y_lr_pred

In [18]:
y_test

2764    61.73
2270    51.88
1993    64.63
2462    68.55
2130    55.49
        ...
2518    80.04
157     45.61
2566    86.91
2003    53.56
238     51.06
Name: Pass_Chance_Percentage, Length: 559, dtype: float64

In [19]:
print("Linear Regression Results:")
print(f"R^2 Score: {r2_score(y_test, y_lr_pred):.4f}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_lr_pred):.4f}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_lr_pred):.4f}")
print(f"Root Mean Squared Error: {np.sqrt(mean_squared_error(y_test, y_lr_pred)):.4f}")

Linear Regression Results:
R^2 Score: 0.7690
Mean Absolute Error: 4.3364
Mean Squared Error: 29.7473
Root Mean Squared Error: 5.4541

In [20]:
print("Coefficients:", model_lr.coef_)

Coefficients: [ -0.1389843   13.32336127  10.62015864   6.00248531  11.46145513
  12.67583639   5.73726941   9.45188958 -11.29665324   5.11738436]

In [21]:
print("Intercept:", model_lr.intercept_)

Intercept: 27.18125949292351

In [22]:
# New student samples
new_students = pd.DataFrame({
    "Gender": [0, 1, 0, 1, 0, 1],
    "Attendance_Percentage": [95, 80, 65, 45, 88, 5],
    "Assignment_Average": [90, 75, 60, 40, 85, 5],
    "Quiz_Average": [92, 72, 58, 35, 82, 60],
    "Midterm_Marks": [88, 78, 55, 38, 84, 65],
    "Study_Hours_Per_Week": [18, 12, 7, 3, 15, 1],
    "Previous_Module_Marks": [86, 74, 58, 42, 80, 5],
    "Class_Participation_Score": [9, 7, 5, 3, 8, 6],
    "Missed_Assignments": [0, 1, 3, 7, 1, 2],
    "LMS_Activity_Hours_Per_Week": [16, 11, 6, 2, 14, 9]
})

new_students

,Gender,Attendance_Percentage,Assignment_Average,Quiz_Average,Midterm_Marks,Study_Hours_Per_Week,Previous_Module_Marks,Class_Participation_Score,Missed_Assignments,LMS_Activity_Hours_Per_Week
0,0,95,90,92,88,18,86,9,0,16
1,1,80,75,72,78,12,74,7,1,11
2,0,65,60,58,55,7,58,5,3,6
3,1,45,40,35,38,3,42,3,7,2
4,0,88,85,82,84,15,80,8,1,14
5,1,5,5,60,65,1,5,6,2,9

In [23]:
new_students_scaled = scaler.transform(new_students)

new_students_scaled

array([[ 0.        ,  0.91896272,  0.85294118,  0.88148148,  0.8136646 ,
         0.86868687,  0.80609418,  0.88888889,  0.        ,  0.82901554],
       [ 1.        ,  0.67585089,  0.63235294,  0.58518519,  0.65838509,
         0.56565657,  0.6398892 ,  0.66666667,  0.16666667,  0.56994819],
       [ 0.        ,  0.43273906,  0.41176471,  0.37777778,  0.30124224,
         0.31313131,  0.41828255,  0.44444444,  0.5       ,  0.31088083],
       [ 1.        ,  0.10858995,  0.11764706,  0.03703704,  0.03726708,
         0.11111111,  0.1966759 ,  0.22222222,  1.16666667,  0.10362694],
       [ 0.        ,  0.80551053,  0.77941176,  0.73333333,  0.7515528 ,
         0.71717172,  0.72299169,  0.77777778,  0.16666667,  0.7253886 ],
       [ 1.        , -0.53970827, -0.39705882,  0.40740741,  0.45652174,
         0.01010101, -0.31578947,  0.55555556,  0.33333333,  0.46632124]])

In [24]:
new_predictions = model_lr.predict(new_students_scaled)

new_predictions

array([91.38034528, 71.99770093, 49.55249561, 22.37603694, 81.62609102,
       25.50069289])

## random forest

In [25]:
model = RandomForestRegressor()
model.fit(X_train_scaled, y_train)

RandomForestRegressor()

In [26]:
y_pred = model.predict(X_test_scaled)
y_pred

array([63.1675, 62.8111, 66.9919, 70.3999, 67.2347, 56.9827, 76.1096,
       47.7794, 60.53  , 74.8806, 58.6126, 68.5038, 61.8497, 72.7308,
       63.9291, 71.8168, 67.4142, 80.0763, 68.4498, 67.2909, 74.6233,
       47.8681, 70.6851, 68.1505, 56.9177, 52.8749, 74.9658, 77.5515,
       61.6053, 54.2056, 62.8978, 80.6318, 65.4763, 54.2514, 67.3735,
       63.0108, 73.5387, 66.861 , 64.0015, 57.627 , 82.2167, 80.2502,
       65.0239, 58.9309, 61.4465, 76.351 , 72.0349, 72.2383, 77.7787,
       53.7019, 43.4105, 63.8094, 54.9732, 44.9118, 62.8223, 64.4499,
       61.7205, 65.9239, 63.4502, 53.7287, 59.1467, 47.6251, 75.1501,
       66.1588, 85.6059, 66.2223, 66.8345, 61.2518, 70.0832, 63.8663,
       72.4459, 64.9904, 80.025 , 46.9836, 74.13  , 76.1323, 63.637 ,
       61.7169, 69.5482, 77.1429, 74.408 , 60.1853, 57.2917, 52.9352,
       53.6192, 65.6195, 80.8233, 69.76  , 64.6657, 55.8738, 53.5775,
       63.1914, 64.4754, 64.2382, 73.0495, 75.6685, 44.565 , 75.7211,
       80.6759, 73.6097, 70.1652, 51.8518, 61.1482, 59.292 , 51.515 ,
       68.8334, 79.7166, 73.9763, 64.2346, 63.2749, 65.9588, 70.3973,
       44.8229, 75.6248, 82.3133, 72.0198, 65.9594, 60.0074, 87.787 ,
       69.3983, 64.2855, 54.7762, 70.4859, 63.9734, 75.7601, 72.0245,
       73.6328, 73.2025, 70.3949, 66.5285, 64.7382, 56.5317, 61.7308,
       73.7819, 68.3849, 73.0403, 65.1694, 58.0293, 75.2817, 54.5517,
       69.1254, 58.8922, 61.6786, 52.8474, 47.6603, 84.399 , 74.1655,
       66.3514, 65.8389, 76.9909, 69.9525, 61.506 , 70.0568, 68.9388,
       77.6787, 76.0327, 72.8265, 57.2923, 62.4225, 66.5726, 76.931 ,
       73.6381, 45.7904, 64.6152, 72.4099, 52.425 , 66.7849, 70.0945,
       77.3727, 73.8568, 60.8947, 60.8718, 83.8239, 72.3181, 46.8177,
       66.0764, 69.8369, 64.3774, 67.7095, 57.3708, 60.3117, 50.748 ,
       62.0057, 70.2334, 71.9469, 63.0505, 69.377 , 72.4905, 68.6351,
       58.7829, 64.2816, 65.8352, 71.9929, 70.1406, 58.5539, 71.4804,
       71.9001, 51.7303, 50.0287, 50.319 , 50.7961, 57.5068, 77.2504,
       62.2967, 70.3606, 83.5969, 67.4569, 64.8268, 54.697 , 69.0071,
       58.8539, 75.4269, 59.394 , 59.721 , 64.3959, 63.1178, 56.9613,
       57.4317, 76.4546, 73.5096, 66.9706, 66.6453, 54.7482, 62.3834,
       59.6056, 61.7685, 54.853 , 62.9721, 56.0703, 68.0943, 55.1006,
       64.7027, 73.0052, 49.4966, 62.8596, 72.8075, 75.4623, 67.8384,
       68.8351, 68.4822, 82.4752, 59.8762, 65.1536, 50.7623, 72.3433,
       67.8676, 74.3426, 56.9494, 60.7268, 55.1483, 77.1058, 71.2393,
       64.6454, 53.0123, 66.6428, 45.7998, 76.8546, 70.4737, 77.2683,
       61.4121, 59.9054, 52.3027, 65.8973, 66.6383, 51.9405, 63.6502,
       86.3118, 66.1452, 51.763 , 63.764 , 71.989 , 45.7523, 67.0314,
       74.0685, 50.692 , 72.0457, 63.1744, 67.1473, 63.0672, 62.3952,
       72.7621, 59.451 , 71.9273, 42.5501, 60.1608, 56.1133, 83.3883,
       72.6875, 55.3943, 68.9427, 73.1266, 71.6907, 54.7447, 65.7788,
       57.7963, 66.0683, 57.3381, 43.2714, 45.4254, 70.2111, 63.9424,
       70.4841, 84.0738, 47.0868, 55.5884, 54.5202, 71.2011, 64.69  ,
       54.5068, 54.2433, 54.6322, 51.4572, 67.0308, 63.7296, 68.8138,
       61.2462, 70.14  , 57.6337, 78.4939, 59.6577, 62.2869, 73.4388,
       48.6691, 84.5175, 60.1688, 53.7093, 54.1409, 64.6091, 66.8629,
       55.762 , 73.3459, 59.6788, 73.2009, 69.5794, 56.9641, 64.6107,
       71.8857, 51.6196, 71.6068, 72.0479, 70.2367, 70.2822, 72.0919,
       61.7519, 70.2322, 63.4324, 65.5942, 80.679 , 51.302 , 50.2247,
       69.614 , 50.8239, 72.0976, 48.4728, 72.5001, 70.6773, 52.8659,
       55.3372, 65.4869, 52.7977, 75.6222, 71.6403, 56.7639, 48.5517,
       76.0453, 56.6207, 71.485 , 50.1702, 74.7395, 74.2955, 69.1941,
       56.143 , 62.8378, 69.3967, 55.7885, 58.7122, 72.0244, 70.3803,
       57.8962, 67.0499, 49.7018, 60.3266, 75.2699, 61.8197, 62.105 ,
       71.2342, 80.2782, 60.0626, 75.3093, 55.9396, 58.0895, 75.3852,
       68.7203, 72.8856, 70.6883, 69.0578, 79.6444, 69.5623, 69.4423,
       57.086 , 67.1139, 75.5793, 59.7172, 49.9581, 68.621 , 64.2775,
       62.9466, 45.4763, 76.0406, 75.1397, 65.206 , 76.9058, 45.9893,
       81.0893, 54.6535, 64.0263, 72.8674, 75.2901, 64.7485, 53.8477,
       58.2296, 62.4112, 73.1982, 78.5108, 70.0274, 78.8758, 57.447 ,
       59.2959, 54.9183, 70.5954, 68.7909, 63.2836, 84.7396, 55.6563,
       80.5064, 49.1823, 62.9215, 48.2651, 46.522 , 61.256 , 63.2511,
       68.8179, 67.6875, 63.9773, 66.9219, 62.4643, 52.0607, 78.6635,
       57.9787, 48.3299, 64.3032, 63.7129, 47.316 , 67.3652, 45.571 ,
       46.0137, 87.439 , 59.3527, 55.6116, 65.1183, 63.3266, 58.8104,
       68.057 , 61.5594, 65.7144, 64.7455, 78.8062, 51.652 , 63.9264,
       56.307 , 77.6967, 53.1467, 80.8093, 51.3162, 47.4021, 51.1919,
       79.6657, 59.4849, 83.3317, 71.3569, 54.8152, 77.1885, 60.4848,
       54.885 , 79.1879, 62.1697, 50.9616, 59.8709, 54.2007, 71.1534,
       55.6105, 62.2905, 63.2339, 61.8582, 65.2595, 58.5081, 55.0072,
       52.7592, 67.5544, 52.181 , 80.2384, 73.6631, 60.0501, 62.6643,
       67.7233, 58.6828, 57.2604, 59.3074, 73.7729, 75.2482, 52.7694,
       62.7999, 65.3677, 64.5507, 54.5385, 66.5033, 48.15  , 69.1343,
       66.3049, 59.6518, 70.4348, 63.8905, 67.6804, 57.7233, 66.5987,
       63.6125, 67.4306, 60.0306, 77.4339, 75.4571, 54.3897, 43.3258,
       61.0006, 72.6109, 60.8539, 74.2491, 58.5443, 67.538 , 75.8703,
       55.4099, 62.4947, 67.9563, 57.9858, 80.3152, 60.2138, 70.2433,
       82.347 , 63.7353, 80.3414, 56.3049, 49.1341, 63.0017, 72.0459,
       69.5505, 79.6105, 50.3633, 78.87  , 57.344 , 52.1777])

In [27]:
y_test

2764    61.73
2270    51.88
1993    64.63
2462    68.55
2130    55.49
        ...
2518    80.04
157     45.61
2566    86.91
2003    53.56
238     51.06
Name: Pass_Chance_Percentage, Length: 559, dtype: float64

In [28]:
print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

4.8007084078711975
35.071467427620746
0.727705998837592

In [29]:
X_test.columns

Index(['Gender', 'Attendance_Percentage', 'Assignment_Average', 'Quiz_Average',
       'Midterm_Marks', 'Study_Hours_Per_Week', 'Previous_Module_Marks',
       'Class_Participation_Score', 'Missed_Assignments',
       'LMS_Activity_Hours_Per_Week'],
      dtype='str')

## Testing no new sample

In [30]:
# New student samples
new_students = pd.DataFrame({
    "Gender": [0, 1, 0, 1, 0],
    "Attendance_Percentage": [95, 80, 65, 45, 88],
    "Assignment_Average": [90, 75, 60, 40, 85],
    "Quiz_Average": [92, 72, 58, 35, 82],
    "Midterm_Marks": [88, 78, 55, 38, 84],
    "Study_Hours_Per_Week": [18, 12, 7, 3, 15],
    "Previous_Module_Marks": [86, 74, 58, 42, 80],
    "Class_Participation_Score": [9, 7, 5, 3, 8],
    "Missed_Assignments": [0, 1, 3, 7, 1],
    "LMS_Activity_Hours_Per_Week": [16, 11, 6, 2, 14]
})

new_students

,Gender,Attendance_Percentage,Assignment_Average,Quiz_Average,Midterm_Marks,Study_Hours_Per_Week,Previous_Module_Marks,Class_Participation_Score,Missed_Assignments,LMS_Activity_Hours_Per_Week
0,0,95,90,92,88,18,86,9,0,16
1,1,80,75,72,78,12,74,7,1,11
2,0,65,60,58,55,7,58,5,3,6
3,1,45,40,35,38,3,42,3,7,2
4,0,88,85,82,84,15,80,8,1,14

In [31]:
new_students_scaled = scaler.transform(new_students)

new_students_scaled

array([[0.        , 0.91896272, 0.85294118, 0.88148148, 0.8136646 ,
        0.86868687, 0.80609418, 0.88888889, 0.        , 0.82901554],
       [1.        , 0.67585089, 0.63235294, 0.58518519, 0.65838509,
        0.56565657, 0.6398892 , 0.66666667, 0.16666667, 0.56994819],
       [0.        , 0.43273906, 0.41176471, 0.37777778, 0.30124224,
        0.31313131, 0.41828255, 0.44444444, 0.5       , 0.31088083],
       [1.        , 0.10858995, 0.11764706, 0.03703704, 0.03726708,
        0.11111111, 0.1966759 , 0.22222222, 1.16666667, 0.10362694],
       [0.        , 0.80551053, 0.77941176, 0.73333333, 0.7515528 ,
        0.71717172, 0.72299169, 0.77777778, 0.16666667, 0.7253886 ]])

In [32]:
new_students_scaled = pd.DataFrame(
    scaler.transform(new_students),
    columns=new_students.columns
)

new_students_scaled

,Gender,Attendance_Percentage,Assignment_Average,Quiz_Average,Midterm_Marks,Study_Hours_Per_Week,Previous_Module_Marks,Class_Participation_Score,Missed_Assignments,LMS_Activity_Hours_Per_Week
0,0.0,0.918963,0.852941,0.881481,0.813665,0.868687,0.806094,0.888889,0.000000,0.829016
1,1.0,0.675851,0.632353,0.585185,0.658385,0.565657,0.639889,0.666667,0.166667,0.569948
2,0.0,0.432739,0.411765,0.377778,0.301242,0.313131,0.418283,0.444444,0.500000,0.310881
3,1.0,0.108590,0.117647,0.037037,0.037267,0.111111,0.196676,0.222222,1.166667,0.103627
4,0.0,0.805511,0.779412,0.733333,0.751553,0.717172,0.722992,0.777778,0.166667,0.725389

In [33]:
new_predictions = model.predict(new_students_scaled)

new_predictions

array([88.616 , 71.4621, 50.6174, 39.2539, 79.6205])