In [1]:
### loading librayimport pandas as pdi
import pandas as pdi
import matplotlib.pyplot as plt from sklearn.preprocessing import LabelEncoder

SyntaxError: invalid syntax (3582157297.py, line 3)

In [ ]:
file = "dataset/student_placement_data.csv"
df = pdi.read_csv(file)
df.head()

   Feature_ID  Math_Score  ICT_Score Gender      Program
0           1        78.0       76.0      M  Electronics
1           2         NaN       49.0      F   Mechanical
2           3        68.0       49.0      M   Mechanical
3           4        54.0       58.0      M   Automotive
4           5        82.0       56.0      M   Mechanical

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Feature_ID  1000 non-null   int64
 1   Math_Score  950 non-null    float64
 2   ICT_Score   950 non-null    float64
 3   Gender      970 non-null    str
 4   Program     1000 non-null   str
dtypes: float64(2), int64(1), str(2)
memory usage: 39.2 KB

In [ ]:
df.describe()

        Feature_ID  Math_Score   ICT_Score
count  1000.000000  950.000000  950.000000
mean    500.500000   70.863158   70.060000
std     288.819436   17.654816   17.245808
min       1.000000   40.000000   40.000000
25%     250.750000   56.000000   56.000000
50%     500.500000   71.000000   70.000000
75%     750.250000   86.750000   85.000000
max    1000.000000  100.000000  100.000000

In [ ]:
df.min()

Feature_ID             1
Math_Score          40.0
ICT_Score           40.0
Gender                 F
Program       Automotive
dtype: object

In [ ]:
df.Math_Score.min()

np.float64(40.0)

In [ ]:
df.['Math_Score'].median()

SyntaxError: invalid syntax (3414597287.py, line 1)

In [ ]:
###show all columns
df.columns

Index(['Math_Score', 'ICT_Score', 'Gender', 'Program'], dtype='str')

In [ ]:
df = df.drop('Feature_ID', axis=1)

KeyError: "['Feature_ID'] not found in axis"

In [ ]:
##check missing values
df=df.isna()